X=mean(channe3_cueN,1);
Y=mean(channe3_cueP,1);
subplot(233);
plot(X,'r');
hold on;
plot(Y,'b');
hold on;
X=channe3_cueN(1,:);
Y=channe3_cueP(1,:);
plot(X,'y');
hold on;
plot(Y,'k');

X=mean(channe4_cueN,1);
Y=mean(channe5_cueP,1);
subplot(234);
plot(X,'r');
hold on;
plot(Y,'b');
hold on;
X=channe4_cueN(1,:);
Y=channe4_cueP(1,:);
plot(X,'y');
hold on;
plot(Y,'k');

X=mean(channe5_cueN,1);
Y=mean(channe5_cueP,1);
subplot(235);
plot(X,'r');
hold on;
plot(Y,'b');
hold on;
X=channe5_cueN(1,:);
Y=channe5_cueP(1,:);
plot(X,'y');
hold on;
plot(Y,'k');

X=mean(channe6_cueN,1);
Y=mean(channe6_cueP,1);
subplot(236);
plot(X,'r');
hold on;
plot(Y,'b');
hold on;
X=channe6_cueN(1,:);
Y=channe6_cueP(1,:);
plot(X,'y');
hold on;
plot(Y,'k');